# Generated by Django 5.0.2 on 2024-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_alter_ticket_category_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='employee_number',
            field=models.CharField(default='UNKNOWN', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itasset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
