# Generated by Django 5.0.2 on 2024-08-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itasset_employee_number_alter_itasset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itasset',
            old_name='assigned_to',
            new_name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='employee_number',
        ),
    ]
