# Generated by Django 5.0.2 on 2024-08-06 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_assigned_to_itasset_assigned_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itasset',
            old_name='assigned_by',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='itasset',
            name='contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itasset',
            name='employee_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
