# Generated by Django 5.0.2 on 2024-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_itasset_employee_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved')], default='unresolved', max_length=20),
        ),
    ]
